# Generated by Django 4.1.7 on 2023-03-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('idade', models.IntegerField(verbose_name='Idade')),
                ('email', models.EmailField(max_length=120, verbose_name='Email')),
                ('cpf', models.CharField(max_length=15, verbose_name='CPF')),
                ('cep', models.IntegerField(verbose_name='CEP (Cidade, Estado, País)')),
            ],
        ),
    ]
