# Generated by Django 4.1.7 on 2023-03-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Informe o valor'),
        ),
    ]
