# Generated by Django 4.1.7 on 2023-03-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0002_alter_receita_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_receita', models.CharField(max_length=8, verbose_name='Informe qual o tipo de receita')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Informe o valor')),
            ],
        ),
    ]
