# Generated by Django 4.1.7 on 2023-03-09 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0003_teste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=75, verbose_name='Titulo da solicitação')),
                ('conteudo', models.CharField(max_length=125, verbose_name='Conteudo da solicitação')),
                ('pendencia', models.BooleanField(verbose_name='Pendencia')),
                ('adm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.gerenciador')),
            ],
        ),
    ]
