# Generated by Django 4.1.7 on 2023-03-09 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0004_solicitacoes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
