# Generated by Django 4.1.7 on 2023-03-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0007_teste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacoes',
            name='pendencia',
            field=models.BooleanField(default=False),
        ),
    ]
