# Generated by Django 4.1.7 on 2023-03-10 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0008_alter_solicitacoes_pendencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitacoes',
            old_name='pendencia',
            new_name='concluido',
        ),
    ]
