# Generated by Django 4.1.7 on 2023-03-10 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0009_rename_pendencia_solicitacoes_concluido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
