# Generated by Django 4.1.7 on 2023-03-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0010_delete_teste'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacoes',
            name='status',
            field=models.CharField(choices=[(False, 'Não Concluído'), (True, 'Concluído')], default='Não Concluído', max_length=11),
        ),
    ]
