# Generated by Django 4.1.7 on 2023-03-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0012_alter_solicitacoes_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacoes',
            name='status',
            field=models.CharField(choices=[(False, 'Não Concluído'), (True, 'Concluído')], default='Não Concluído', max_length=20),
        ),
    ]
