# Generated by Django 4.1.7 on 2023-03-10 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0013_alter_solicitacoes_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacoes',
            name='status',
        ),
    ]
