# Generated by Django 4.1.7 on 2023-03-12 12:10

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0014_remove_solicitacoes_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=150, verbose_name='Nome do produto')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço unitario')),
                ('estoque', models.IntegerField(verbose_name='Estoque disponivel')),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to='produtos', variations={'thumb': {'crop': True, 'height': 300, 'width': 450}}, verbose_name='Imagem do Produto')),
                ('postado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.gerenciador')),
            ],
        ),
    ]
