# Generated by Django 4.1.7 on 2023-03-13 19:09

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0019_produto_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='produto', variations={'thumb': {'crop': True, 'height': 300, 'width': 300}}, verbose_name='Imagem do produto'),
        ),
    ]
