# Generated by Django 4.1.7 on 2023-03-13 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0020_alter_produto_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='postado_por',
        ),
        migrations.DeleteModel(
            name='Receita',
        ),
        migrations.RemoveField(
            model_name='solicitacoes',
            name='adm',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='produto',
        ),
        migrations.DeleteModel(
            name='CategoriaProduto',
        ),
        migrations.DeleteModel(
            name='Gerenciador',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='Solicitacoes',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
