# Generated by Django 4.1.7 on 2023-03-13 19:16

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adm', '0021_remove_produto_categoria_remove_produto_postado_por_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=25, verbose_name='Nome da categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Gerenciador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('idade', models.IntegerField(verbose_name='Idade')),
                ('email', models.EmailField(max_length=120, verbose_name='Email')),
                ('cpf', models.CharField(max_length=15, verbose_name='CPF')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=150, verbose_name='Nome do produto')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço unitario')),
                ('estoque', models.IntegerField(verbose_name='Estoque disponivel')),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to='produto', variations={'thumb': {'crop': True, 'height': 300, 'width': 300}}, verbose_name='Imagem do produto')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True, verbose_name='Slug')),
                ('categoria', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adm.categoriaproduto')),
                ('postado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.gerenciador')),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_receita', models.CharField(max_length=8, verbose_name='Informe qual o tipo de receita')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Informe o valor')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('data_venda', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=75, verbose_name='Titulo da solicitação')),
                ('conteudo', models.CharField(max_length=125, verbose_name='Conteudo da solicitação')),
                ('concluido', models.BooleanField(default=False)),
                ('adm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.gerenciador')),
            ],
        ),
    ]
